name: Test & Build

on:
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash
    working-directory: ./

permissions:
  contents: read

env:
  DO_NOT_TRACK: 1

jobs:
  test:
    runs-on: ubuntu-x64
    permissions:
      contents: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
          fetch-depth: 1
          persist-credentials: false
      - name: Setup NodeJS environment
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version-file: .nvmrc
          cache: yarn
      - name: Install frontend dependencies
        run: yarn install --frozen-lockfile;
      - name: Spellcheck
        run: yarn spellcheck;
      - name: Setup Go environment
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: "go.work"
          cache-dependency-path: "**/*.sum"
      - name: Validate environment
        run: |
          echo "-------- node version -----"
          node --version
          echo "-------- npm version -----"
          npm --version
          echo "-------- yarn version -----"
          yarn --version
          echo "-------- go version -----"
          go version
      - name: Test
        run: yarn test
