name: Test & Build

on:
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash
    working-directory: ./

permissions:
  contents: read

env:
  DO_NOT_TRACK: 1

jobs:
  test:
    runs-on: ubuntu-x64
    permissions:
      contents: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
          fetch-depth: 1
          persist-credentials: false
      - name: Setup NodeJS environment
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .nvmrc
          cache: yarn
      - name: Install frontend dependencies
        run: yarn install --frozen-lockfile;
      - name: Spellcheck
        run: yarn spellcheck;
      - name: Setup Go environment
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: "go.work"
          cache-dependency-path: "**/*.sum"
      - name: Validate environment
        run: |
          echo "-------- node version -----"
          node --version
          echo "-------- npm version -----"
          npm --version
          echo "-------- yarn version -----"
          yarn --version
          echo "-------- go version -----"
          go version
      - name: Test
        run: yarn test
