name: Backed libraries
on:
  pull_request:
    paths:
      - "lib/go/**"
  push:
    branches:
      - main
    paths:
      - "lib/go/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go environment
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.1"
      - name: Validate environment
        run: |
          echo "-------- node version -----"
          node --version
          echo "-------- npm version -----"
          npm --version
          echo "-------- yarn version -----"
          yarn --version
          echo "-------- go version -----"
          go version
      - name: Test backend
        run: npx --package=turbo@latest -- turbo test:backend
